/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.HoKhauPanelController;
import javax.swing.JFrame;
import views.HoKhauManagerFrame.ChuyenDiNoiKhac;
import views.HoKhauManagerFrame.TachHoKhau;
import views.HoKhauManagerFrame.ThemMoiHoKhau;

/**
 *
 * @author Ai làm thì diền tên vào
 */
public class HoKhauManagePanel extends javax.swing.JPanel {
    
    private JFrame parentFrame;
    private HoKhauPanelController controller;
    /**
     * Creates new form HoKhauManagePanel
     */
    public HoKhauManagePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        controller = new HoKhauPanelController(jtfSearch, tableJpn);
        controller.setParentJFrame(parentFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themMoiBtn = new javax.swing.JButton();
        tachHoKhauBtn = new javax.swing.JButton();
        chuyenDiBtn = new javax.swing.JButton();
        tableJpn = new javax.swing.JPanel();
        jtfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        themMoiBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        themMoiBtn.setText("Thêm mới");
        themMoiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMoiBtnActionPerformed(evt);
            }
        });
        add(themMoiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 130, 30));

        tachHoKhauBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tachHoKhauBtn.setText("Tách hộ khẩu");
        tachHoKhauBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tachHoKhauBtnActionPerformed(evt);
            }
        });
        add(tachHoKhauBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 130, 30));

        chuyenDiBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chuyenDiBtn.setText("Chuyển đi");
        chuyenDiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenDiBtnActionPerformed(evt);
            }
        });
        add(chuyenDiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 130, 30));

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        add(tableJpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 650, 389));

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSearchActionPerformed(evt);
            }
        });
        add(jtfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin hộ khẩu");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void chuyenDiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenDiBtnActionPerformed
        ChuyenDiNoiKhac chuyenDiNoiKhac = new ChuyenDiNoiKhac(this.parentFrame);
        chuyenDiNoiKhac.setLocationRelativeTo(null);
        chuyenDiNoiKhac.setResizable(false);
        chuyenDiNoiKhac.setVisible(true);
    }//GEN-LAST:event_chuyenDiBtnActionPerformed

    private void themMoiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiBtnActionPerformed
        ThemMoiHoKhau themMoiHoKhau = new ThemMoiHoKhau(this.parentFrame);
        themMoiHoKhau.setLocationRelativeTo(null);
        themMoiHoKhau.setResizable(false);
        themMoiHoKhau.setVisible(true);
    }//GEN-LAST:event_themMoiBtnActionPerformed

    private void tachHoKhauBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tachHoKhauBtnActionPerformed
        TachHoKhau tachHoKhau = new TachHoKhau(this.parentFrame);
        tachHoKhau.setLocationRelativeTo(null);
        tachHoKhau.setResizable(false);
        tachHoKhau.setVisible(true);
    }//GEN-LAST:event_tachHoKhauBtnActionPerformed

    private void jtfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSearchActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chuyenDiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JButton tachHoKhauBtn;
    private javax.swing.JButton themMoiBtn;
    // End of variables declaration//GEN-END:variables
}
