package views;

import controllers.ThongKePanelController;
import javax.swing.JFrame;

/**
 *
 * @author ai làm thì điền tên vô
 */
public class ThongKePanel extends javax.swing.JPanel {
    private JFrame parentFrame;
    private ThongKePanelController controller;
    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
        this.controller = new ThongKePanelController(GenderJcb, StatusJcb, tuTuoiJtf, denTuoiJtf, tuNamJtf, denNamJtf, tableJpn);
        this.controller.setDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderChoose = new javax.swing.ButtonGroup();
        statusChoose = new javax.swing.ButtonGroup();
        tableJpn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuTuoiJtf = new javax.swing.JTextField();
        denTuoiJtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tuNamJtf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        denNamJtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        GenderJcb = new javax.swing.JComboBox<>();
        StatusJcb = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout tableJpnLayout = new javax.swing.GroupLayout(tableJpn);
        tableJpn.setLayout(tableJpnLayout);
        tableJpnLayout.setHorizontalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tableJpnLayout.setVerticalGroup(
            tableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        add(tableJpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 731, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tình trạng:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 15, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Độ tuổi:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 62, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Từ:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 62, -1, 30));

        tuTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tuTuoiJtf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(tuTuoiJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 51, 30));

        denTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        denTuoiJtf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(denTuoiJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 51, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("-");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 62, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("Tuổi");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 63, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 104, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Giới tính:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 15, -1, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Năm:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 62, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Từ:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 62, -1, 30));

        tuNamJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tuNamJtf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(tuNamJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 51, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("-");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 62, -1, 30));

        denNamJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        denNamJtf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        add(denNamJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 51, 30));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Hiển thị");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 102, -1));

        GenderJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GenderJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Nam", "Nữ" }));
        add(GenderJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, 90, 30));

        StatusJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        StatusJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Thường trú", "Tạm trú", "Tạm vắng" }));
        add(StatusJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 15, 164, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.controller.setData();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderChoose;
    private javax.swing.JComboBox<String> GenderJcb;
    private javax.swing.JComboBox<String> StatusJcb;
    private javax.swing.JTextField denNamJtf;
    private javax.swing.JTextField denTuoiJtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup statusChoose;
    private javax.swing.JPanel tableJpn;
    private javax.swing.JTextField tuNamJtf;
    private javax.swing.JTextField tuTuoiJtf;
    // End of variables declaration//GEN-END:variables
}
